import { CourtStatus, CourtSurface } from '../../common/constants/common.constant';
import { CourtEntity } from '../entities/court.entity';

export type CourtSeedItem = Omit<Partial<CourtEntity>, 'timeSlots'> & {
  timeSlots: Array<{ start: number; end: number; price: number }>;
};

export const courtSeedData: CourtSeedItem[] = [
  {
    name: 'Sân A1',
    location: 'Tầng 1 - Khu A',
    courtCode: 'C000001',
    status: CourtStatus.ACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=900&q=80',
    description: 'Sân trong nhà tiêu chuẩn thi đấu',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.PVC,
    roofHeight: 12,
    isIndoor: true,
    hasConditioning: true,
    hasFans: true,
    isActive: true,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '22:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 8, price: 80000 },
      { start: 8, end: 10, price: 100000 },
      { start: 17, end: 19, price: 150000 },
      { start: 19, end: 21, price: 180000 },
    ],
  },
  {
    name: 'Sân A2',
    location: 'Tầng 1 - Khu A',
    courtCode: 'C000002',
    status: CourtStatus.ACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1599394022918-6c2776530abb?auto=format&fit=crop&w=900&q=80',
    description: 'Sân trong nhà, phù hợp tập luyện',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.HARDCOURT,
    roofHeight: 10,
    isIndoor: true,
    hasConditioning: false,
    hasFans: true,
    isActive: true,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '22:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 8, price: 70000 },
      { start: 8, end: 10, price: 90000 },
      { start: 17, end: 19, price: 140000 },
      { start: 19, end: 21, price: 160000 },
    ],
  },
  {
    name: 'Sân A3',
    location: 'Tầng 1 - Khu A',
    courtCode: 'C000004',
    status: CourtStatus.ACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1554068865-24cecd4e343f?auto=format&fit=crop&w=900&q=80',
    description: 'Sân đôi tiêu chuẩn, có máy lạnh',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.PVC,
    roofHeight: 11,
    isIndoor: true,
    hasConditioning: true,
    hasFans: true,
    isActive: true,
    isMaintenance: false,
    openingHours: '05:00',
    endingHours: '23:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 5, end: 8, price: 75000 },
      { start: 8, end: 17, price: 110000 },
      { start: 17, end: 21, price: 160000 },
      { start: 21, end: 23, price: 130000 },
    ],
  },
  {
    name: 'Sân A4 VIP',
    location: 'Tầng 1 - Khu A',
    courtCode: 'C000005',
    status: CourtStatus.ACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1613918431703-aa50481936b0?auto=format&fit=crop&w=900&q=80',
    description: 'Sân VIP mặt gỗ, trần cao, máy lạnh 2 chiều',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.HARDCOURT,
    roofHeight: 13,
    isIndoor: true,
    hasConditioning: true,
    hasFans: false,
    isActive: true,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '23:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 12, price: 150000 },
      { start: 12, end: 17, price: 180000 },
      { start: 17, end: 23, price: 220000 },
    ],
  },
  {
    name: 'Sân B1',
    location: 'Tầng 2 - Khu B',
    courtCode: 'C000003',
    status: CourtStatus.UNDER_MAINTENANCE,
    imageUrl:
      'https://images.unsplash.com/photo-1461896836934-ffe607ba6851?auto=format&fit=crop&w=900&q=80',
    description: 'Sân đang bảo trì mặt sàn',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.SYNTHETIC_GRASS,
    roofHeight: 9,
    isIndoor: false,
    hasConditioning: false,
    hasFans: false,
    isActive: false,
    isMaintenance: true,
    openingHours: '06:00',
    endingHours: '21:00',
    reasonForMaintenance: 'Thay mặt sàn',
    timeSlots: [
      { start: 7, end: 9, price: 60000 },
      { start: 16, end: 18, price: 100000 },
    ],
  },
  {
    name: 'Sân B2',
    location: 'Tầng 2 - Khu B',
    courtCode: 'C000006',
    status: CourtStatus.ACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=900&q=80',
    description: 'Sân ngoài trời mặt cỏ nhân tạo',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.SYNTHETIC_GRASS,
    roofHeight: 0,
    isIndoor: false,
    hasConditioning: false,
    hasFans: false,
    isActive: true,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '21:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 10, price: 60000 },
      { start: 10, end: 16, price: 80000 },
      { start: 16, end: 21, price: 120000 },
    ],
  },
  {
    name: 'Sân B3',
    location: 'Tầng 2 - Khu B',
    courtCode: 'C000007',
    status: CourtStatus.ACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1599394022918-6c2776530abb?auto=format&fit=crop&w=900&q=80',
    description: 'Sân đôi ngoài trời, ánh sáng LED',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.HARDCOURT,
    roofHeight: 0,
    isIndoor: false,
    hasConditioning: false,
    hasFans: false,
    isActive: true,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '22:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 11, price: 65000 },
      { start: 11, end: 17, price: 85000 },
      { start: 17, end: 22, price: 130000 },
    ],
  },
  {
    name: 'Sân C1',
    location: 'Tầng trệt - Khu C',
    courtCode: 'C000008',
    status: CourtStatus.ACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1554068865-24cecd4e343f?auto=format&fit=crop&w=900&q=80',
    description: 'Sân đơn trong nhà, phù hợp tập kỹ thuật',
    width: 13.4,
    height: 5.18,
    peopleCapacity: 2,
    surface: CourtSurface.CARPET,
    roofHeight: 8,
    isIndoor: true,
    hasConditioning: true,
    hasFans: true,
    isActive: true,
    isMaintenance: false,
    openingHours: '07:00',
    endingHours: '22:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 7, end: 12, price: 70000 },
      { start: 12, end: 17, price: 90000 },
      { start: 17, end: 22, price: 120000 },
    ],
  },
  {
    name: 'Sân C2',
    location: 'Tầng trệt - Khu C',
    courtCode: 'C000009',
    status: CourtStatus.ACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1613918431703-aa50481936b0?auto=format&fit=crop&w=900&q=80',
    description: 'Sân clay trong nhà, cảm giác bóng tốt',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.CLAY,
    roofHeight: 10,
    isIndoor: true,
    hasConditioning: false,
    hasFans: true,
    isActive: true,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '22:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 10, price: 90000 },
      { start: 10, end: 17, price: 110000 },
      { start: 17, end: 22, price: 150000 },
    ],
  },
  {
    name: 'Sân C3',
    location: 'Tầng trệt - Khu C',
    courtCode: 'C000010',
    status: CourtStatus.INACTIVE,
    imageUrl:
      'https://images.unsplash.com/photo-1461896836934-ffe607ba6851?auto=format&fit=crop&w=900&q=80',
    description: 'Sân tạm ngưng hoạt động',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.PVC,
    roofHeight: 9,
    isIndoor: true,
    hasConditioning: false,
    hasFans: true,
    isActive: false,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '21:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 12, price: 70000 },
      { start: 17, end: 21, price: 120000 },
    ],
  },
];
