import { CourtStatus, CourtSurface } from '../../common/constants/common.constant';
import { CourtEntity } from '../entities/court.entity';

export type CourtSeedItem = Omit<Partial<CourtEntity>, 'timeSlots'> & {
  timeSlots: Array<{ start: number; end: number; price: number }>;
};

export const courtSeedData: CourtSeedItem[] = [
  {
    name: 'Sân A1',
    location: 'Tầng 1 - Khu A',
    courtCode: 'C000001',
    status: CourtStatus.ACTIVE,
    imageUrl: '/courts/a1.jpg',
    description: 'Sân trong nhà tiêu chuẩn thi đấu',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.PVC,
    roofHeight: 12,
    isIndoor: true,
    hasConditioning: true,
    hasFans: true,
    isActive: true,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '22:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 8, price: 80000 },
      { start: 8, end: 10, price: 100000 },
      { start: 17, end: 19, price: 150000 },
      { start: 19, end: 21, price: 180000 },
    ],
  },
  {
    name: 'Sân A2',
    location: 'Tầng 1 - Khu A',
    courtCode: 'C000002',
    status: CourtStatus.ACTIVE,
    imageUrl: '/courts/a2.jpg',
    description: 'Sân trong nhà, phù hợp tập luyện',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.HARDCOURT,
    roofHeight: 10,
    isIndoor: true,
    hasConditioning: false,
    hasFans: true,
    isActive: true,
    isMaintenance: false,
    openingHours: '06:00',
    endingHours: '22:00',
    reasonForMaintenance: '',
    timeSlots: [
      { start: 6, end: 8, price: 70000 },
      { start: 8, end: 10, price: 90000 },
      { start: 17, end: 19, price: 140000 },
      { start: 19, end: 21, price: 160000 },
    ],
  },
  {
    name: 'Sân B1',
    location: 'Tầng 2 - Khu B',
    courtCode: 'C000003',
    status: CourtStatus.UNDER_MAINTENANCE,
    imageUrl: '/courts/b1.jpg',
    description: 'Sân đang bảo trì mặt sàn',
    width: 13.4,
    height: 6.1,
    peopleCapacity: 4,
    surface: CourtSurface.SYNTHETIC_GRASS,
    roofHeight: 9,
    isIndoor: false,
    hasConditioning: false,
    hasFans: false,
    isActive: false,
    isMaintenance: true,
    openingHours: '06:00',
    endingHours: '21:00',
    reasonForMaintenance: 'Thay mặt sân',
    timeSlots: [
      { start: 7, end: 9, price: 60000 },
      { start: 16, end: 18, price: 100000 },
    ],
  },
];
